@include('admin-page.layout.head')
@include('admin-page.layout.header')
@include('admin-page.layout.sidebar')
@include('admin-page.layout.content.addProduct.form')
@include('admin-page.layout.footer')