@include('admin-page.layout.head')
@include('admin-page.layout.header')
@include('admin-page.layout.sidebar')
@include('admin-page.layout.content.customer.list')
@include('admin-page.layout.content.customer.jsSearchCustomer')
@include('admin-page.layout.footer')